"""Industry Knowledge Packs (Startup Domain Intelligence Sprint, Phase 2; expanded in the Master
Startup Knowledge Base Sprint, Phases 2-3).

Reference data, not a reasoning engine — the same role app.agents.venture_vocabulary's `_VOCAB`
and app.agents.go_to_market_intelligence's `_GTM_VOCAB`/app.agents.feature_intelligence's
`_FEATURE_IDEAS` already play: a hand-curated, versioned, category-keyed dict of general
startup-domain knowledge, keyed by the same taxonomy app.agents.venture_vocabulary.resolve_category
already resolves every venture into (no new classifier, no new taxonomy — this sprint only added
more categories to that one existing resolver). Every fact here is qualitative, general
startup-operating knowledge — never a specific statistic, percentage, named real company, or price,
which is exactly what would turn "domain knowledge" into a fabricated claim. Deliberately excludes a
"common competitors" field: naming real companies at the category level (rather than the per-venture,
retrieval/description-derived competitors already surfaced elsewhere in the pipeline) would itself be
a fabrication risk this sprint's own rules forbid. Consumed by app.agents.startup_benchmark,
app.agents.founder_intelligence, app.agents.pricing_intelligence, and
app.agents.go_to_market_intelligence as shared reference context, never as a second, independent
recommendation engine — the actual founder-facing recommendation always still comes from those
existing modules' own venture-specific reasoning.
"""

from __future__ import annotations

from app.agents.venture_vocabulary import resolve_category

INDUSTRY_KNOWLEDGE_PACK_VERSION = "v2"

_PACKS: dict[str, dict] = {
    "healthcare": {
        "typical_customer": "A clinical department, independent practice, or health system operations team.",
        "buying_process": "Clinical champion identifies the need, then a slow multi-stakeholder review (clinical + IT + compliance) before any purchase order — rarely a single decision-maker.",
        "customer_journey": ["Clinician/department head feels the pain", "Informal trial or shadow use", "IT/security review", "Compliance sign-off", "Departmental budget approval", "Rollout to the rest of the department"],
        "common_integrations": ["EHR/EMR systems", "Practice management software", "Lab/diagnostic information systems"],
        "expected_kpis": ["Clinician time saved per case", "Patient outcome/adherence trend", "Reduction in missed follow-ups or errors"],
        "procurement_difficulty": "high — clinical and compliance review cycles routinely take months, even for a small pilot.",
        "procurement_cycle": "Typically several months from first clinical conversation to signed pilot, driven by IT/security and compliance review, not budget alone.",
        "sales_cycle": "Long and relationship-driven — trust with a clinical champion has to be earned before any commercial conversation starts.",
        "enterprise_objections": ["Where is the clinical evidence this actually improves outcomes?", "How does this integrate with our existing EHR without duplicate data entry?", "What happens to patient data if your company shuts down?"],
        "smb_objections": ["Can a small practice with limited IT staff actually set this up?", "Is this worth it for our patient volume?"],
        "pilot_strategy": "One department or independent practice, one clinician champion, a short supervised pilot with a single measurable clinical or workflow outcome.",
        "expansion_path": "Prove the outcome in one department, then expand to adjacent departments in the same institution before selling to a new institution.",
        "expansion_triggers": ["A documented outcome improvement the champion can present internally", "A second department asking to adopt after seeing the first department's results"],
        "customer_acquisition_channels": ["Clinical conference/association relationships", "Referrals from an existing champion to peers at other institutions", "Direct outreach to department heads"],
        "retention_strategy": "Stay embedded in the clinical workflow so removing the tool means reverting to a worse manual process; keep proving the outcome at renewal time with real usage data.",
        "common_pricing_approaches": ["Per-clinician or per-site licensing", "Tiered by number of patients/cases handled"],
        "common_failure_reasons": ["Underestimating the length of the compliance/procurement cycle", "No clinical champion willing to advocate internally", "Integration friction with existing EHR workflows"],
        "common_competitive_advantages": ["Deep EHR integration", "Clinical validation/evidence", "Compliance-ready data handling from day one"],
        "enterprise_readiness_checklist": ["HIPAA-aligned data handling", "EHR integration or export path", "Audit logging for clinical data access", "Business associate agreement readiness"],
        "regulatory_considerations": "Patient data handling (HIPAA-equivalent), and clinical claims about outcomes typically require supporting evidence before being marketed.",
        "technical_stack_expectations": "Ability to integrate with or export to standard clinical data formats (e.g. HL7/FHIR-style interoperability); on-prem or private-cloud deployment options are often expected by larger institutions.",
        "typical_differentiation": "Depth of EHR/clinical-workflow integration and demonstrated real-world outcome evidence, more than raw feature count.",
        "common_feature_roadmap": ["Start with one workflow step (e.g. documentation or scheduling)", "Add outcome tracking/reporting", "Add EHR-native integration", "Add multi-department/multi-site rollout tooling"],
    },
    "insurance": {
        "typical_customer": "An underwriting, claims, or actuarial team at an insurer, MGA, or brokerage.",
        "buying_process": "A design-partner conversation with an underwriting or claims lead, followed by a compliance and data-security review before any policy or claims volume moves through the product.",
        "customer_journey": ["Underwriting/claims lead identifies a manual or slow process", "Design-partner discussion", "Compliance/security review", "Small pilot on a limited book of business", "Broader rollout across product lines"],
        "common_integrations": ["Policy administration systems", "Claims management systems", "Actuarial/rating engines"],
        "expected_kpis": ["Underwriting or claims turnaround time", "Loss ratio impact (where measurable)", "Manual review hours saved"],
        "procurement_difficulty": "high — regulatory and data-security review is a hard gate, and insurers are typically conservative about vendor risk.",
        "procurement_cycle": "Often several months, gated by compliance/legal review of data handling and any use of the tool in regulated decisions (e.g. underwriting or claims determinations).",
        "sales_cycle": "Long, technical, and evidence-driven — insurers want to see the tool perform on their own historical data before committing.",
        "enterprise_objections": ["How does this affect our regulatory filings or rate approvals?", "Can we audit every decision this tool influences?", "What happens to policyholder data if you shut down?"],
        "smb_objections": ["Can a smaller MGA/brokerage justify this without a large book of business?"],
        "pilot_strategy": "One limited book of business or claims segment, reviewed alongside compliance from day one, with a clear before/after comparison.",
        "expansion_path": "Prove value on one segment or line of business, then expand to adjacent lines before pursuing a full policy-administration integration.",
        "expansion_triggers": ["A measurable improvement on the pilot segment", "Compliance sign-off achieved once, making the next line of business faster to approve"],
        "customer_acquisition_channels": ["Industry conferences and actuarial/underwriting associations", "Warm introductions via reinsurers or brokers", "Direct outreach to underwriting/claims leadership"],
        "retention_strategy": "Demonstrate ongoing loss-ratio or efficiency impact at each renewal; regulatory switching costs (re-filing, re-audit) make insurers reluctant to churn once integrated.",
        "common_pricing_approaches": ["Per-policy or per-claim usage pricing", "Tiered by book-of-business size"],
        "common_failure_reasons": ["Underestimating regulatory/compliance review timelines", "No auditable explanation for decisions the tool influences", "Selling to a line of business too small to justify the integration effort"],
        "common_competitive_advantages": ["Auditable, explainable decisioning", "Integration with existing policy/claims systems", "Demonstrated performance on real historical data"],
        "enterprise_readiness_checklist": ["Auditable decision trail", "Data handling that satisfies insurance-regulatory review", "Integration with policy administration/claims systems"],
        "regulatory_considerations": "Insurance is a heavily regulated, state/jurisdiction-specific industry — any tool influencing underwriting or claims decisions should expect regulatory scrutiny and auditability requirements.",
        "technical_stack_expectations": "Batch and/or API integration with policy administration and claims systems; explainable-decisioning capability is often expected, not optional.",
        "typical_differentiation": "Auditability and explainability of decisions, plus demonstrated performance on the insurer's own historical data.",
        "common_feature_roadmap": ["Start with one decision point (e.g. triage or first-pass review)", "Add auditability/explainability reporting", "Add policy-system integration", "Expand to additional lines of business"],
    },
    "fintech": {
        "typical_customer": "A finance, operations, or compliance team at a company processing payments, lending, or financial data.",
        "buying_process": "A design-partner conversation first, then a compliance/security review before any transaction volume moves through the product.",
        "customer_journey": ["Operator identifies a manual/compliance pain point", "Design-partner discussion", "Security/compliance review", "Small pilot with limited transaction volume", "Full integration and volume ramp-up"],
        "common_integrations": ["Accounting/ledger software", "Banking or payment processor APIs", "KYC/identity verification providers"],
        "expected_kpis": ["Transaction volume processed", "Reconciliation time saved", "Error/dispute rate"],
        "procurement_difficulty": "high — compliance and security review is usually a hard gate, even for a small pilot.",
        "procurement_cycle": "Weeks to a few months, largely dependent on how quickly security/compliance review clears rather than the commercial decision itself.",
        "sales_cycle": "Medium-to-long, technical, and trust-driven — proof of reliability at small scale precedes any real volume commitment.",
        "enterprise_objections": ["What's your security/compliance certification status?", "How do you handle a transaction dispute or error?", "What happens to our financial data if you're acquired or shut down?"],
        "smb_objections": ["Is the integration effort worth it for our transaction volume?"],
        "pilot_strategy": "A single design partner with real but limited transaction volume, reviewed alongside compliance from day one rather than after the fact.",
        "expansion_path": "Prove reliability at low volume with one partner, then expand transaction volume before adding new partners.",
        "expansion_triggers": ["A clean track record at low volume with no unresolved disputes/errors", "A partner requesting higher volume/limits"],
        "customer_acquisition_channels": ["Fintech/operations community referrals", "Direct outreach to finance/ops leads", "Partnerships with banks or payment processors"],
        "retention_strategy": "Reliability track record and reconciliation accuracy are the retention lever — a single serious error can undo months of trust.",
        "common_pricing_approaches": ["Usage-based pricing tied to transaction volume", "Tiered by account/transaction limits"],
        "common_failure_reasons": ["Underestimating compliance review timelines", "Trying to sell to enterprise finance teams before proving reliability at small scale", "Security review failures late in the sales cycle"],
        "common_competitive_advantages": ["Direct integration with existing financial systems", "Demonstrated compliance posture", "Reliability track record at real transaction volume"],
        "enterprise_readiness_checklist": ["SOC 2-equivalent security posture", "Documented compliance/data-handling practices", "SSO and audit logging for finance-team access"],
        "regulatory_considerations": "Financial data handling, KYC/AML obligations where applicable, and data residency/security expectations from banking partners.",
        "technical_stack_expectations": "API-first integration with accounting/ledger and payment-processor systems; strong emphasis on auditability and error handling.",
        "typical_differentiation": "Demonstrated reliability and compliance posture at real transaction volume, not feature breadth.",
        "common_feature_roadmap": ["Start with one workflow (e.g. reconciliation or one payment type)", "Add compliance/audit reporting", "Add broader integration coverage", "Expand transaction types/volume limits"],
    },
    "cybersecurity": {
        "typical_customer": "A security or engineering lead responsible for a specific system, pipeline, or compliance obligation.",
        "buying_process": "A security/engineering lead evaluates technical credibility first (often via a free scoped assessment), then a budget conversation once real findings exist.",
        "customer_journey": ["Security lead becomes aware of a gap or compliance deadline", "Free/low-cost scoped assessment", "Internal review of findings", "Budget approval tied to a compliance deadline", "Subscription/ongoing engagement"],
        "common_integrations": ["CI/CD pipelines", "SIEM/logging systems", "Ticketing systems (Jira, etc.)"],
        "expected_kpis": ["Number/severity of findings resolved", "Time-to-remediation", "Compliance framework coverage"],
        "procurement_difficulty": "medium-to-high — often gated by a compliance deadline (SOC 2, ISO 27001), which can accelerate OR stall a decision depending on timing.",
        "procurement_cycle": "Can be fast when tied to an active compliance deadline; otherwise weeks-to-months while the security team evaluates credibility.",
        "sales_cycle": "Evidence-first — a credible finding from a real scoped assessment does more selling than any pitch.",
        "enterprise_objections": ["Why should we trust a new vendor with security-sensitive access?", "How is this different from our existing tooling?", "What's your own security posture and incident history?"],
        "smb_objections": ["Do we have the internal capacity to act on the findings this surfaces?"],
        "pilot_strategy": "One scoped assessment or single environment/asset, with a concrete, credible finding as the proof point before any subscription conversation.",
        "expansion_path": "One scoped engagement proving real findings, then expand to continuous coverage, then to additional environments/asset types.",
        "expansion_triggers": ["A credible finding acted on successfully", "An upcoming compliance audit/deadline"],
        "customer_acquisition_channels": ["Security community/conference presence", "Content demonstrating real findings/technique", "Referrals from security practitioners"],
        "retention_strategy": "Continuous coverage renewal is driven by ongoing findings and compliance-framework mapping staying current as the customer's environment changes.",
        "common_pricing_approaches": ["Per-asset or per-environment scanned pricing", "Compliance-framework-mapped tiers"],
        "common_failure_reasons": ["Leading with features instead of a credible, concrete finding", "Underestimating the trust barrier of security-sensitive access", "No clear compliance-deadline trigger to anchor the sale"],
        "common_competitive_advantages": ["Real, demonstrated findings/evidence (not just claims)", "Compliance-framework-mapped reporting", "Low-friction, credible first engagement"],
        "enterprise_readiness_checklist": ["Least-privilege access model", "Compliance-framework mapped reporting (SOC 2/ISO 27001-style)", "Own security posture documented and auditable"],
        "regulatory_considerations": "Compliance frameworks the customer must satisfy (e.g. SOC 2, ISO 27001, industry-specific mandates) shape both what the tool must report and how access is scoped.",
        "technical_stack_expectations": "Integration with CI/CD and logging/SIEM systems; least-privilege, auditable access to any scanned environment.",
        "typical_differentiation": "Credibility of real findings and how cleanly reporting maps to the compliance frameworks the customer already has to satisfy.",
        "common_feature_roadmap": ["Start with one scan/assessment type", "Add compliance-framework-mapped reporting", "Add continuous/ongoing monitoring", "Expand asset/environment coverage"],
    },
    "legaltech": {
        "typical_customer": "An individual attorney, in-house counsel, or a small legal operations team.",
        "buying_process": "An attorney trials the tool on a real matter first; firm-wide or in-house adoption requires a partner/GC-level approval and often an IT/security review for confidentiality.",
        "customer_journey": ["Attorney discovers the tool for a specific task (review, research, drafting)", "Trial on one real matter", "Informal advocacy to colleagues", "Partner/GC or IT security review", "Firm-wide or department-wide rollout"],
        "common_integrations": ["Document management systems", "Practice management software", "E-signature/e-filing platforms"],
        "expected_kpis": ["Time saved per matter/document", "Reduction in review errors or missed clauses", "Matters handled per attorney"],
        "procurement_difficulty": "medium-to-high — client confidentiality and malpractice-risk concerns mean security/ethics review is common even for a single-attorney trial.",
        "procurement_cycle": "Weeks for an individual trial; months for firm-wide or in-house department adoption pending IT/security and partner approval.",
        "sales_cycle": "Trust-driven — attorneys need to see accurate output on their own real documents before advocating internally.",
        "enterprise_objections": ["How do you guarantee client confidentiality and privilege are preserved?", "What's your liability if the tool makes an error on a matter?", "Does this integrate with our document management system?"],
        "smb_objections": ["Is this worth it for a small practice with a handful of attorneys?"],
        "pilot_strategy": "One attorney on one real (non-sensitive, if possible) matter, measured against time saved and output accuracy.",
        "expansion_path": "Prove value with one attorney on one matter type, then expand to adjacent matter types or additional attorneys before firm-wide rollout.",
        "expansion_triggers": ["A documented time-savings or accuracy result the champion can show partners", "A second practice group requesting access"],
        "customer_acquisition_channels": ["Bar association and legal-tech conference presence", "Referrals between attorneys", "Direct outreach to practice-group leads"],
        "retention_strategy": "Accuracy and confidentiality track record are the retention lever; renewal hinges on continued trust with sensitive client matters.",
        "common_pricing_approaches": ["Per-attorney/per-seat licensing", "Per-matter or usage-based pricing"],
        "common_failure_reasons": ["An early accuracy error that breaks trust with a confidentiality-sensitive profession", "No integration with the firm's existing document management system", "Underestimating how conservative legal buyers are about new tools"],
        "common_competitive_advantages": ["Demonstrated accuracy on real legal documents", "Confidentiality/security posture attorneys can vouch for", "Document management system integration"],
        "enterprise_readiness_checklist": ["Confidentiality/privilege-preserving data handling", "Audit trail for document access and changes", "Document management system integration"],
        "regulatory_considerations": "Attorney-client privilege and confidentiality obligations, and jurisdiction-specific bar/ethics rules about use of automated tools in legal work.",
        "technical_stack_expectations": "Integration with common document management and practice management systems; strong data isolation between client matters.",
        "typical_differentiation": "Demonstrated accuracy on real legal work plus a confidentiality/security posture attorneys are willing to vouch for.",
        "common_feature_roadmap": ["Start with one task (review, research, or drafting)", "Add matter/document-management integration", "Add collaboration features for a practice group", "Expand to firm-wide administration and reporting"],
    },
    "hrtech": {
        "typical_customer": "An HR, people-ops, or talent-acquisition lead at a company hiring or managing employees.",
        "buying_process": "An HR/people-ops lead trials the tool for one hiring cycle or process; broader adoption requires budget approval and often an IT/security review for employee data.",
        "customer_journey": ["HR lead identifies a pain point (hiring, onboarding, performance)", "Trial during one hiring cycle or review period", "Internal advocacy to leadership", "IT/security and budget approval", "Company-wide rollout"],
        "common_integrations": ["HRIS/payroll systems", "Applicant tracking systems", "Calendar/scheduling tools"],
        "expected_kpis": ["Time-to-hire or time-to-fill", "Onboarding time/completion rate", "HR team time saved per cycle"],
        "procurement_difficulty": "medium — usually one HR decision-maker, but employee-data handling triggers an IT/security review at larger companies.",
        "procurement_cycle": "Weeks for smaller companies; a couple of months for larger ones pending security review and budget cycle alignment.",
        "sales_cycle": "Practical and outcome-focused — HR buyers want to see time saved on a real hiring cycle or review period.",
        "enterprise_objections": ["How do you handle employee data privacy?", "Does this integrate with our HRIS/payroll system?", "What happens to employee data if you shut down?"],
        "smb_objections": ["Is this overkill for a small team without a dedicated HR function?"],
        "pilot_strategy": "One hiring cycle, department, or review period, measured against a concrete time-saved or completion-rate outcome.",
        "expansion_path": "Prove the outcome in one hiring cycle or department, then expand to additional departments or the full employee lifecycle before company-wide rollout.",
        "expansion_triggers": ["A measurable time-to-hire or onboarding improvement", "A second department requesting access after seeing results"],
        "customer_acquisition_channels": ["HR community/conference presence", "Referrals between people-ops professionals", "Direct outreach to HR leads"],
        "retention_strategy": "Embed in the recurring hiring/review cycle so the tool becomes the default workflow; renew by showing cycle-over-cycle time savings.",
        "common_pricing_approaches": ["Per-employee or per-hire pricing", "Per-seat pricing for the HR team"],
        "common_failure_reasons": ["No integration with the existing HRIS/payroll system", "Underestimating employee-data privacy concerns", "A tool that adds work for hiring managers instead of removing it"],
        "common_competitive_advantages": ["HRIS/ATS integration", "Demonstrated time savings across a real hiring or review cycle", "A privacy-respecting data handling story"],
        "enterprise_readiness_checklist": ["Employee data privacy compliance", "HRIS/payroll integration", "Role-based access controls"],
        "regulatory_considerations": "Employee data privacy laws and, where hiring decisions are involved, anti-discrimination/fair-hiring considerations for any automated screening.",
        "technical_stack_expectations": "Integration with common HRIS/ATS/payroll platforms; role-based access so sensitive employee data is appropriately scoped.",
        "typical_differentiation": "Depth of HRIS/ATS integration and demonstrated time savings across a real hiring or review cycle.",
        "common_feature_roadmap": ["Start with one process (hiring, onboarding, or reviews)", "Add HRIS/ATS integration", "Add reporting/analytics for HR leadership", "Expand across the full employee lifecycle"],
    },
    "proptech": {
        "typical_customer": "A property manager, landlord, or commercial real estate operations team.",
        "buying_process": "A property/facilities manager trials on one building or portfolio segment; broader adoption requires ownership or asset-management approval, often tied to a lease-renewal or budget cycle.",
        "customer_journey": ["Manager identifies an operational pain point (leasing, maintenance, tenant communication)", "Trial on one property", "Internal advocacy to ownership/asset management", "Budget approval, often aligned to a fiscal or lease cycle", "Rollout across the portfolio"],
        "common_integrations": ["Property management software", "Accounting/billing systems", "Building access/IoT systems where applicable"],
        "expected_kpis": ["Vacancy/lease-up time", "Maintenance response time", "Tenant satisfaction/retention"],
        "procurement_difficulty": "medium — often gated by the property's own budget cycle and integration with existing property management software.",
        "procurement_cycle": "Weeks for a single-property trial; can stretch to a full budget cycle (often quarterly or annual) for portfolio-wide adoption.",
        "sales_cycle": "Relationship- and results-driven — real estate operators want proof from a comparable property type before expanding.",
        "enterprise_objections": ["Does this integrate with our existing property management system?", "How does this scale across a diverse portfolio (different building types/ages)?", "What's the disruption to tenants during rollout?"],
        "smb_objections": ["Is this worth it for a small landlord with only a few units?"],
        "pilot_strategy": "One property or a small portfolio segment, measured against a concrete operational metric like vacancy time or maintenance response time.",
        "expansion_path": "Prove the outcome on one property, then expand to similar property types in the same portfolio before pursuing new ownership groups.",
        "expansion_triggers": ["A measurable operational improvement on the pilot property", "Budget cycle alignment for portfolio-wide rollout"],
        "customer_acquisition_channels": ["Real estate industry conferences/associations", "Referrals between property managers", "Direct outreach to asset management firms"],
        "retention_strategy": "Retention tracks with lease-renewal cycles — demonstrate operational impact ahead of each budget/renewal cycle.",
        "common_pricing_approaches": ["Per-unit or per-property pricing", "Portfolio-wide tiered licensing"],
        "common_failure_reasons": ["No integration with the property's existing management software", "Underestimating how budget cycles (not just interest) gate expansion", "A tool that works for one building type but not the portfolio's diversity"],
        "common_competitive_advantages": ["Property management system integration", "Demonstrated operational improvement on a real property", "Ability to handle diverse building types within one portfolio"],
        "enterprise_readiness_checklist": ["Integration with property management software", "Multi-property/portfolio administration", "Tenant data privacy handling"],
        "regulatory_considerations": "Tenant/resident data privacy, and local housing or commercial-leasing regulations depending on jurisdiction and property type.",
        "technical_stack_expectations": "Integration with common property management/accounting systems; ability to support multiple properties/units under one account.",
        "typical_differentiation": "Depth of property management system integration and proven operational impact across a diverse portfolio.",
        "common_feature_roadmap": ["Start with one operational workflow (leasing, maintenance, or communication)", "Add property management system integration", "Add portfolio-level reporting", "Expand to multi-property administration"],
    },
    "retailtech": {
        "typical_customer": "A store manager, merchandising lead, or retail operations team.",
        "buying_process": "A store or merchandising manager typically decides for a single location directly; multi-location or chain adoption requires a regional or corporate operations sign-off.",
        "customer_journey": ["Manager feels a pain point (inventory, checkout, merchandising)", "Trial at one store location", "Manager decides directly or escalates to regional ops", "Rollout to additional locations"],
        "common_integrations": ["POS systems", "Inventory management software", "E-commerce platforms where applicable"],
        "expected_kpis": ["Inventory accuracy/stock-out rate", "Checkout/transaction time", "Sales lift or conversion rate"],
        "procurement_difficulty": "low for a single independent store; medium-to-high for chain/franchise operators who require corporate or regional sign-off.",
        "procurement_cycle": "Fast (days to weeks) for a single independent store; a full budget or planning cycle for chain-wide rollout.",
        "sales_cycle": "Numbers-driven — retail buyers respond to clear before/after metrics from a real store.",
        "enterprise_objections": ["Does this integrate with our existing POS/inventory system?", "How does this perform across different store formats/sizes?", "What's the rollout disruption during business hours?"],
        "smb_objections": ["Is this worth the setup effort for a single small store?"],
        "pilot_strategy": "One store location, running for a defined period, with inventory accuracy or checkout time as the measurable outcome.",
        "expansion_path": "Prove the outcome at one store, then expand to additional stores in the same chain/region before pursuing new retail groups.",
        "expansion_triggers": ["A measurable improvement at the pilot store", "Regional/corporate ops requesting rollout after seeing results"],
        "customer_acquisition_channels": ["Retail trade shows/associations", "Referrals between store or regional managers", "Direct outreach to retail operations leadership"],
        "retention_strategy": "Ongoing measurable impact on inventory/sales metrics, reviewed at seasonal or annual planning cycles.",
        "common_pricing_approaches": ["Per-store or per-terminal pricing", "Transaction/usage-based pricing"],
        "common_failure_reasons": ["No real POS/inventory integration", "A tool that works for one store format but not others in the chain", "Underestimating how disruptive changes are during active business hours"],
        "common_competitive_advantages": ["Direct POS/inventory integration", "Proven sales or accuracy improvement at a real store", "Low operational disruption during rollout"],
        "enterprise_readiness_checklist": ["Multi-location administration", "POS/inventory system integration", "Consistent performance across store formats"],
        "regulatory_considerations": "Payment-data handling (PCI-style expectations where transactions are involved) and consumer data privacy where customer data is collected.",
        "technical_stack_expectations": "Integration with common POS and inventory systems; reliable operation during peak in-store hours.",
        "typical_differentiation": "Real POS/inventory integration and a proven, measurable outcome at an actual store rather than a demo environment.",
        "common_feature_roadmap": ["Start with one workflow (inventory, checkout, or merchandising)", "Add POS/inventory integration", "Add multi-store reporting", "Expand to chain-wide administration"],
    },
    "travel_hospitality": {
        "typical_customer": "A hotel/property operations manager, tour operator, or travel booking platform team.",
        "buying_process": "A property or operations manager trials on one property or route; multi-property or brand-wide adoption requires regional or brand-level approval, often tied to a booking season.",
        "customer_journey": ["Manager identifies a pain point (booking, guest experience, operations)", "Trial at one property or on one route", "Results reviewed against a booking season", "Rollout to additional properties/routes"],
        "common_integrations": ["Property/booking management systems", "Channel managers/OTAs", "Payment processing"],
        "expected_kpis": ["Booking conversion rate", "Guest satisfaction/review scores", "Operational time saved per booking/stay"],
        "procurement_difficulty": "medium — often gated by seasonal timing (avoiding disruption during peak season) and integration with existing booking systems.",
        "procurement_cycle": "Timed around booking seasons — decisions often cluster in the off-season to avoid disrupting peak operations.",
        "sales_cycle": "Seasonal and proof-driven — operators want to see results from one season before committing further.",
        "enterprise_objections": ["Does this integrate with our channel manager/booking system?", "What happens during peak season if something breaks?", "How does this perform across different property types/regions?"],
        "smb_objections": ["Is this worth it for a single small property or boutique operator?"],
        "pilot_strategy": "One property or route for a single booking season, measured against booking conversion or guest satisfaction.",
        "expansion_path": "Prove the outcome for one property/route in one season, then expand to additional properties/routes before pursuing brand-wide adoption.",
        "expansion_triggers": ["A measurable improvement in one booking season", "Brand/regional leadership requesting expansion after seeing results"],
        "customer_acquisition_channels": ["Hospitality industry conferences/associations", "Referrals between property operators", "Partnerships with booking platforms/OTAs"],
        "retention_strategy": "Demonstrate season-over-season improvement; renewal decisions often align with annual booking-season planning.",
        "common_pricing_approaches": ["Per-property or per-booking pricing", "Commission/percentage-of-booking pricing"],
        "common_failure_reasons": ["No real integration with the property's booking/channel management system", "Rolling out changes during peak season and causing disruption", "A tool proven for one property type but not others"],
        "common_competitive_advantages": ["Booking/channel manager integration", "Demonstrated seasonal performance improvement", "Reliability during peak operational periods"],
        "enterprise_readiness_checklist": ["Channel manager/booking system integration", "Multi-property administration", "Reliability guarantees for peak-season operation"],
        "regulatory_considerations": "Consumer/guest data privacy, payment processing compliance, and jurisdiction-specific travel/hospitality regulations where applicable.",
        "technical_stack_expectations": "Integration with property/booking management systems and channel managers; must perform reliably under peak-season load.",
        "typical_differentiation": "Real booking-system integration and a proven result from an actual booking season, not a demo environment.",
        "common_feature_roadmap": ["Start with one workflow (booking, guest communication, or operations)", "Add channel manager integration", "Add multi-property reporting", "Expand to brand-wide administration"],
    },
    "govtech": {
        "typical_customer": "A program lead or department within a government agency (municipal, state/provincial, or federal).",
        "buying_process": "Formal RFP/procurement process is common even for small engagements; an agency program lead champions the tool internally while procurement rules dictate the actual buying mechanism.",
        "customer_journey": ["Agency program lead identifies a need", "Informal conversation or pilot request", "Formal procurement/RFP process", "Budget approval within a fiscal cycle", "Rollout within the agency/department"],
        "common_integrations": ["Existing case management or citizen-service systems", "Public records/data systems"],
        "expected_kpis": ["Citizen/constituent service time", "Case processing time", "Cost savings versus prior process"],
        "procurement_difficulty": "high — formal procurement rules, budget-cycle timing, and public-accountability requirements make this one of the slowest buying processes of any category.",
        "procurement_cycle": "Often 6-12+ months, aligned to the agency's fiscal year and formal procurement/RFP requirements.",
        "sales_cycle": "Long, process-heavy, and relationship-dependent — an internal champion navigating procurement rules matters as much as the product itself.",
        "enterprise_objections": ["Can this pass our procurement/security review requirements?", "How is public data protected and who is accountable?", "What happens to continuity of service if your company changes hands?"],
        "smb_objections": ["N/A — govtech buyers are typically agencies, not small businesses; the closest equivalent is a small municipality asking whether this scales down to their budget and staff size."],
        "pilot_strategy": "One department or program within a single agency, run as a pilot or proof-of-concept explicitly scoped to fit within procurement exceptions for small pilots where they exist.",
        "expansion_path": "Prove the outcome in one department, then pursue formal procurement for agency-wide adoption before expanding to additional agencies.",
        "expansion_triggers": ["A successful pilot with documented cost/time savings", "A budget cycle opening for formal procurement"],
        "customer_acquisition_channels": ["Government/public-sector conferences and associations", "Relationships with procurement officers and program leads", "Referrals between agencies (peer-to-peer government networks)"],
        "retention_strategy": "Consistent, reliable service delivery and responsiveness to public-accountability requirements; renewal often re-enters a procurement cycle rather than a simple opt-in.",
        "common_pricing_approaches": ["Per-agency or per-department licensing", "Fixed-term contract pricing tied to budget cycles"],
        "common_failure_reasons": ["Underestimating procurement timelines and requirements", "No plan for the formal RFP process", "Treating a small pilot's success as proof that agency-wide procurement will follow automatically"],
        "common_competitive_advantages": ["Experience navigating public-sector procurement", "Demonstrated cost/time savings in a real agency pilot", "Public-accountability-ready data handling"],
        "enterprise_readiness_checklist": ["Procurement/security review readiness", "Accessibility compliance for public-facing tools", "Data handling that satisfies public-records/accountability requirements"],
        "regulatory_considerations": "Public procurement rules, public-records/accountability obligations, and accessibility requirements for any citizen-facing interface.",
        "technical_stack_expectations": "Ability to integrate with legacy case-management or citizen-service systems; hosting/data-residency requirements are often specific to the jurisdiction.",
        "typical_differentiation": "Demonstrated ability to navigate procurement successfully and a track record of reliable delivery to a public-sector client.",
        "common_feature_roadmap": ["Start with one citizen-service or internal workflow", "Add accessibility-compliant public-facing interface", "Add integration with legacy agency systems", "Expand to additional departments/agencies"],
    },
    "climatetech": {
        "typical_customer": "A sustainability, ESG, or facilities/operations lead at a company measuring or reducing environmental impact.",
        "buying_process": "A sustainability or operations lead trials at one facility or for one reporting cycle; broader adoption ties to the company's sustainability reporting calendar and budget approval.",
        "customer_journey": ["Sustainability/operations lead identifies a measurement or reduction need", "Trial at one facility/site", "Results reviewed against a reporting cycle", "Budget approval", "Rollout across facilities/sites"],
        "common_integrations": ["Energy/utility metering systems", "ESG reporting platforms", "Facility/building management systems"],
        "expected_kpis": ["Measured emissions/energy reduction", "Reporting time saved", "Cost savings from efficiency improvements"],
        "procurement_difficulty": "medium — often tied to a compliance/reporting deadline (e.g. annual ESG disclosure), which can accelerate a decision.",
        "procurement_cycle": "Often aligned to the company's annual sustainability reporting cycle, which can compress or stretch the timeline depending on proximity to the deadline.",
        "sales_cycle": "Evidence- and deadline-driven — a credible measurement result ahead of a reporting deadline is the strongest sales lever.",
        "enterprise_objections": ["How do you verify/audit the measurement methodology?", "Does this satisfy our specific ESG reporting framework?", "What happens to our data if you shut down before our next reporting cycle?"],
        "smb_objections": ["Is formal sustainability measurement worth it for a smaller company without reporting obligations?"],
        "pilot_strategy": "One facility or site, measured for one reporting period, with a clear before/after on the target metric (emissions, energy, waste).",
        "expansion_path": "Prove the measurement/reduction outcome at one facility, then expand to additional facilities ahead of the next reporting cycle.",
        "expansion_triggers": ["A successful, audit-ready result from one reporting cycle", "An approaching regulatory or voluntary disclosure deadline"],
        "customer_acquisition_channels": ["Sustainability/ESG industry conferences", "Referrals between sustainability leads", "Content addressing specific reporting-framework requirements"],
        "retention_strategy": "Stay embedded in the recurring reporting cycle; renewal is driven by needing consistent, auditable data year over year.",
        "common_pricing_approaches": ["Per-facility/per-site pricing", "Subscription tied to reporting-cycle frequency"],
        "common_failure_reasons": ["Measurement methodology that doesn't hold up to audit/verification", "Missing alignment with the specific ESG framework the customer reports under", "Timing a pilot too late to inform the customer's actual reporting deadline"],
        "common_competitive_advantages": ["Auditable, verifiable measurement methodology", "Alignment with recognized ESG reporting frameworks", "Demonstrated results ahead of a real reporting cycle"],
        "enterprise_readiness_checklist": ["Auditable measurement methodology", "Alignment with common ESG reporting frameworks", "Multi-facility data aggregation"],
        "regulatory_considerations": "Emerging and jurisdiction-specific climate disclosure regulations, and the specific voluntary/mandatory ESG reporting framework the customer follows.",
        "technical_stack_expectations": "Integration with energy/utility metering and building management systems; data aggregation across multiple facilities/sites.",
        "typical_differentiation": "Auditable measurement methodology and alignment with the reporting framework the customer actually has to satisfy.",
        "common_feature_roadmap": ["Start with one measurement type (e.g. energy or emissions)", "Add audit-ready reporting", "Add multi-facility aggregation", "Expand to reduction-recommendation features"],
    },
    "agriculture": {
        "typical_customer": "A farm operator, agronomist, or agricultural operations manager.",
        "buying_process": "A farm operator trials on one field or growing season; larger farms or co-ops require an operations-manager or ownership decision, often timed to the planting calendar.",
        "customer_journey": ["Operator identifies a pain point (yield, input cost, pest/disease)", "Trial on one field for one growing season", "Results reviewed at harvest", "Decision to expand for the next season", "Rollout across additional fields/farms"],
        "common_integrations": ["Farm management software", "Equipment/sensor telemetry systems", "Weather data services"],
        "expected_kpis": ["Yield per acre/hectare", "Input cost savings (water, fertilizer, pesticide)", "Time saved on monitoring/decision-making"],
        "procurement_difficulty": "medium — decisions are often timed tightly to the planting/growing calendar, so missing the window can delay adoption a full season.",
        "procurement_cycle": "Seasonal — a decision missed before planting typically means waiting for the next growing season.",
        "sales_cycle": "Proof-driven and seasonal — operators want to see a real yield or cost result from one full season before expanding.",
        "enterprise_objections": ["Does this work with our existing equipment/sensors?", "How reliable is this without connectivity in the field?", "What's the ROI relative to our current input costs?"],
        "smb_objections": ["Is this affordable and simple enough for a small or family farm?"],
        "pilot_strategy": "One field for one growing season, measured against yield, input cost, or time-saved outcomes at harvest.",
        "expansion_path": "Prove the outcome on one field for one season, then expand to additional fields or farms the following season.",
        "expansion_triggers": ["A measurable yield or cost improvement documented at harvest", "The start of a new planting season"],
        "customer_acquisition_channels": ["Agricultural extension services and cooperatives", "Farm equipment dealer partnerships", "Word-of-mouth between operators in the same region"],
        "retention_strategy": "Season-over-season proof of yield/cost impact; renewal aligns with each new planting cycle.",
        "common_pricing_approaches": ["Per-acre/per-hectare pricing", "Per-season subscription pricing"],
        "common_failure_reasons": ["Missing the planting-season window for adoption decisions", "Assuming reliable connectivity that doesn't exist in the field", "No integration with equipment/sensors the operator already owns"],
        "common_competitive_advantages": ["Works with the operator's existing equipment/sensors", "Demonstrated yield or cost improvement over a real season", "Reliable operation without dependable field connectivity"],
        "enterprise_readiness_checklist": ["Offline/low-connectivity operation", "Integration with common farm equipment/sensor telemetry", "Multi-field/multi-farm data aggregation"],
        "regulatory_considerations": "Agricultural input regulations (e.g. pesticide/fertilizer application rules) where the tool influences those decisions, and data ownership expectations for farm-generated data.",
        "technical_stack_expectations": "Ability to operate with limited/offline field connectivity; integration with existing farm equipment and sensor telemetry.",
        "typical_differentiation": "Real integration with the operator's existing equipment and a demonstrated result from an actual growing season.",
        "common_feature_roadmap": ["Start with one measurement/decision type (e.g. irrigation or pest monitoring)", "Add equipment/sensor integration", "Add multi-field reporting", "Expand to predictive/recommendation features"],
    },
    "media": {
        "typical_customer": "An editorial, content operations, or advertising operations lead at a publisher, studio, or platform.",
        "buying_process": "An editorial or content-ops lead trials on one publication or channel; broader adoption requires a budget decision from publishing/platform leadership.",
        "customer_journey": ["Editorial/content lead identifies a pain point (production, distribution, monetization)", "Trial on one title/channel", "Results reviewed against engagement or revenue metrics", "Budget approval", "Rollout across additional titles/channels"],
        "common_integrations": ["Content management systems", "Ad-serving/monetization platforms", "Analytics/audience measurement tools"],
        "expected_kpis": ["Audience engagement/time spent", "Production time saved", "Ad revenue or monetization lift"],
        "procurement_difficulty": "medium — usually one editorial/ops decision-maker, but ad-monetization or data-sharing integrations can trigger a broader review.",
        "procurement_cycle": "Weeks to a couple of months, often timed around content-calendar or advertising-cycle planning.",
        "sales_cycle": "Metrics-driven — publishers respond to clear engagement or revenue lift demonstrated on real content.",
        "enterprise_objections": ["Does this integrate with our CMS/ad stack?", "How does this affect our relationship with our audience/advertisers?", "What's the content-licensing or IP implication of using this?"],
        "smb_objections": ["Is this worth it for a small publication or independent channel?"],
        "pilot_strategy": "One publication or content channel, measured against engagement, production time, or monetization outcomes.",
        "expansion_path": "Prove the outcome on one title/channel, then expand to additional titles/channels within the same publisher.",
        "expansion_triggers": ["A measurable engagement or revenue lift on the pilot title/channel", "A new content season or advertising cycle beginning"],
        "customer_acquisition_channels": ["Media/publishing industry conferences", "Referrals between editorial/content-ops leads", "Direct outreach to publishers/platforms"],
        "retention_strategy": "Ongoing demonstrated engagement or revenue impact; renewal often aligns with advertising or content-planning cycles.",
        "common_pricing_approaches": ["Per-title/per-channel pricing", "Revenue-share or usage-based pricing tied to monetization"],
        "common_failure_reasons": ["No real CMS/ad-stack integration", "Underestimating IP/content-licensing sensitivities", "A tool proven on one content format but not others in the portfolio"],
        "common_competitive_advantages": ["CMS/ad-stack integration", "Demonstrated engagement or monetization lift on real content", "Respect for content-licensing/IP concerns"],
        "enterprise_readiness_checklist": ["CMS/ad-stack integration", "Multi-title/channel administration", "Content-licensing/IP-safe data handling"],
        "regulatory_considerations": "Content licensing/IP rights, advertising-disclosure regulations, and audience data privacy where personalization or targeting is involved.",
        "technical_stack_expectations": "Integration with common CMS and ad-serving/monetization platforms; analytics integration for engagement measurement.",
        "typical_differentiation": "Real CMS/ad-stack integration and a demonstrated engagement or monetization result on actual published content.",
        "common_feature_roadmap": ["Start with one workflow (production, distribution, or monetization)", "Add CMS/ad-stack integration", "Add cross-title analytics", "Expand to portfolio-wide administration"],
    },
    "gaming": {
        "typical_customer": "A game studio producer, live-ops lead, or independent developer.",
        "buying_process": "A producer or live-ops lead trials in a limited playtest or soft launch; broader adoption requires studio leadership approval tied to a title's development or live-ops budget.",
        "customer_journey": ["Producer/dev identifies a pain point (build pipeline, live-ops, monetization, retention)", "Trial in a playtest or soft-launch cohort", "Results reviewed against retention/engagement metrics", "Budget approval", "Integration into the live title or next title"],
        "common_integrations": ["Game engines/SDKs", "Analytics/telemetry platforms", "Live-ops/monetization backends"],
        "expected_kpis": ["Player retention (D1/D7/D30-style)", "Engagement/session metrics", "Monetization/ARPU-style impact"],
        "procurement_difficulty": "medium — technical integration risk (engine/SDK compatibility) matters as much as budget approval.",
        "procurement_cycle": "Often tied to a title's development milestones or live-ops release calendar rather than a fixed procurement rhythm.",
        "sales_cycle": "Proof-driven — studios want to see a measurable retention or engagement impact from a real playtest or soft launch before committing.",
        "enterprise_objections": ["Does this integrate cleanly with our engine/SDK without performance impact?", "How does this affect player experience/trust?", "What's the risk to our live title if this breaks?"],
        "smb_objections": ["Is this worth the integration effort for a small indie studio?"],
        "pilot_strategy": "One playtest cohort or soft-launch region, measured against retention or engagement metrics before wider release.",
        "expansion_path": "Prove the outcome in one playtest/soft launch, then expand to the full live title or the studio's next title.",
        "expansion_triggers": ["A measurable retention/engagement improvement in the pilot cohort", "A new title entering development or live-ops planning"],
        "customer_acquisition_channels": ["Game developer conferences and communities", "Referrals between studios/producers", "Direct outreach to independent developers"],
        "retention_strategy": "Demonstrated, ongoing impact on player retention/engagement metrics; studios renew based on measurable live performance.",
        "common_pricing_approaches": ["Per-title licensing", "Usage-based pricing tied to player volume/sessions"],
        "common_failure_reasons": ["Engine/SDK integration issues affecting performance", "No measurable retention/engagement impact from the pilot", "Underestimating the risk-aversion around anything touching a live title"],
        "common_competitive_advantages": ["Clean, low-overhead engine/SDK integration", "Demonstrated retention or engagement lift from a real playtest", "A track record with live titles, not just prototypes"],
        "enterprise_readiness_checklist": ["Engine/SDK compatibility across major platforms", "Reliable performance under live-title load", "Player data privacy handling"],
        "regulatory_considerations": "Player data privacy (including age-appropriate design where minors may play), and platform-specific policies (console/app-store certification requirements).",
        "technical_stack_expectations": "Integration with common game engines/SDKs and analytics/telemetry platforms; must not introduce meaningful performance overhead.",
        "typical_differentiation": "Low-overhead engine integration and a demonstrated retention/engagement result from a real playtest or soft launch.",
        "common_feature_roadmap": ["Start with one mechanic/workflow (e.g. onboarding or monetization)", "Add analytics/telemetry integration", "Add live-ops tooling", "Expand to additional titles/platforms"],
    },
    "arvr": {
        "typical_customer": "An early-adopter individual user, or an enterprise/institutional partner piloting a specific device-based use case.",
        "buying_process": "Individual consumer adoption is self-serve and device-gated; enterprise/institutional adoption requires a pilot with a specific device and use case before any broader purchase.",
        "customer_journey": ["User/partner identifies a use case suited to AR/VR", "Trial with a specific supported device", "Evaluation of comfort/usability and outcome", "Decision to expand device fleet or user base"],
        "common_integrations": ["AR/VR platform SDKs (headset/device-specific)", "Existing enterprise systems where the use case is training/visualization/collaboration"],
        "expected_kpis": ["Task completion time/accuracy versus the non-AR/VR baseline", "User comfort/session length", "Device/session adoption rate"],
        "procurement_difficulty": "medium-to-high for enterprise use — hardware cost and device-fleet management add a layer procurement doesn't face with pure software.",
        "procurement_cycle": "Gated by hardware availability/cost as much as software evaluation; enterprise pilots often need a hardware budget line separate from software.",
        "sales_cycle": "Experience-driven — a hands-on demo with the actual target device matters more than a slide deck.",
        "enterprise_objections": ["Which specific devices does this support and how do we manage a device fleet?", "What's the comfort/usability track record for extended use?", "Is the ROI over the non-AR/VR alternative actually demonstrated?"],
        "smb_objections": ["N/A — most SMB buyers of AR/VR are actually consumer/prosumer users; the closest equivalent objection is device cost relative to the benefit."],
        "pilot_strategy": "One supported device and one clearly scoped use case, measured against a concrete comfort and task-outcome benchmark.",
        "expansion_path": "Prove the use case on one device with a small group, then expand device count/user base before adding new use cases.",
        "expansion_triggers": ["A demonstrated task-outcome improvement over the non-AR/VR baseline", "Falling device costs or improved device availability"],
        "customer_acquisition_channels": ["AR/VR developer and hardware-platform communities", "Partnerships with device manufacturers", "Direct outreach to enterprise innovation/training teams"],
        "retention_strategy": "Comfort and demonstrated task-outcome improvement drive retention; hardware refresh cycles are a natural re-engagement point.",
        "common_pricing_approaches": ["Per-device or per-seat licensing", "Per-use-case enterprise licensing"],
        "common_failure_reasons": ["Underestimating hardware cost/availability as an adoption barrier", "Comfort/usability issues that undermine a promising use case", "No clear ROI story versus the non-AR/VR alternative"],
        "common_competitive_advantages": ["Broad or well-matched device support for the target use case", "Demonstrated comfort and task-outcome results", "A credible enterprise device-fleet management story"],
        "enterprise_readiness_checklist": ["Device fleet management/administration", "Demonstrated comfort/usability for extended sessions", "Data privacy for any spatial/biometric-adjacent data captured"],
        "regulatory_considerations": "Data privacy for spatial/biometric-adjacent data (e.g. eye tracking, room mapping) where captured, and workplace-safety considerations for extended device use.",
        "technical_stack_expectations": "Integration with device-specific AR/VR SDKs; performance must hold up on the actual target hardware, not just a development rig.",
        "typical_differentiation": "Device support breadth matched to the real use case, and demonstrated comfort/task-outcome results on actual hardware.",
        "common_feature_roadmap": ["Start with one device and one use case", "Add comfort/usability refinements from real sessions", "Add device-fleet administration", "Expand device/use-case support"],
    },
    "creator_economy": {
        "typical_customer": "An individual content creator or a small creator-support team.",
        "buying_process": "Individual, self-serve adoption — the creator tries the tool directly, usually without any institutional approval step, and decides based on early monetization/engagement results.",
        "customer_journey": ["Creator discovers the tool", "First-use activation on their own content/audience", "Evaluation of monetization or engagement impact", "Continued or expanded use"],
        "common_integrations": ["Social/content platforms the creator already publishes on", "Payment/payout processors"],
        "expected_kpis": ["Monetization/revenue per creator", "Audience engagement/growth", "Retention of the creator on the platform"],
        "procurement_difficulty": "very low — no institutional buyer; the hard part is proving monetization value to an individual, not clearing an approval process.",
        "procurement_cycle": "Immediate/self-serve — a creator decides in a single sitting based on perceived value.",
        "sales_cycle": "Short and value-driven — creators adopt quickly if the monetization or growth benefit is clear, and churn quickly if it isn't.",
        "enterprise_objections": ["N/A — creator economy tools rarely face an institutional buyer's objections; the closest equivalent is creator trust around revenue share and payout reliability."],
        "smb_objections": ["Is the revenue share or fee worth it compared to going direct-to-platform?"],
        "pilot_strategy": "A small cohort of creators testing real monetization or engagement impact on their actual audience, not a demo account.",
        "expansion_path": "Prove monetization/engagement impact with a small creator cohort, then broaden acquisition to more creators once payout reliability and value are proven.",
        "expansion_triggers": ["Demonstrated, reliable payout/monetization results for early creators", "Positive word-of-mouth within a creator community"],
        "customer_acquisition_channels": ["Creator communities and creator-focused social platforms", "Referrals from creator to creator", "Influencer/creator partnerships"],
        "retention_strategy": "Reliable, on-time payouts and continued demonstrated monetization/engagement value; creators churn fast if payout trust breaks once.",
        "common_pricing_approaches": ["Revenue-share/take-rate on creator earnings", "Freemium with a paid tier for advanced monetization tools"],
        "common_failure_reasons": ["Payout reliability issues breaking creator trust", "Revenue share perceived as not worth it versus going direct-to-platform", "Acquisition dependent on one platform's algorithm/policy changes"],
        "common_competitive_advantages": ["Reliable, on-time payouts", "Demonstrated monetization or growth impact for real creators", "Low switching friction from the creator's existing platform"],
        "enterprise_readiness_checklist": ["N/A at the individual-creator level — the closest equivalent is reliable payout infrastructure and clear revenue-share terms."],
        "regulatory_considerations": "Payment/payout compliance (tax reporting for creator earnings where applicable) and platform policies of the social/content platforms the tool integrates with.",
        "technical_stack_expectations": "Integration with the social/content platforms creators already use and reliable payment/payout processing.",
        "typical_differentiation": "Payout reliability and demonstrated monetization or growth impact for real creators, not just tooling breadth.",
        "common_feature_roadmap": ["Start with one monetization or engagement mechanic", "Add reliable payout infrastructure", "Add platform integrations", "Expand to additional monetization formats"],
    },
    "hardware": {
        "typical_customer": "An operations, facilities, or engineering lead responsible for a physical site, fleet, or production line (covers robotics, industrial IoT, manufacturing, construction tech, energy, and space-tech ventures, which share this same field-trial-first buying pattern).",
        "buying_process": "A site/operations lead requests a field trial with real hardware before any purchase order; capital-equipment budget approval typically follows a successful trial, not precedes it.",
        "customer_journey": ["Operations/engineering lead identifies a physical-process pain point", "Field trial with real hardware at one site", "Internal review of trial results (safety, reliability, ROI)", "Capital-budget approval", "Rollout to additional sites/units"],
        "common_integrations": ["Existing industrial control/SCADA-style systems", "Fleet/asset management software", "Site sensor/monitoring infrastructure"],
        "expected_kpis": ["Uptime/reliability of the deployed hardware", "Cost or time saved versus the prior process", "Safety incident rate"],
        "procurement_difficulty": "high — capital-equipment purchases usually require a demonstrated field trial and often a formal safety/reliability review.",
        "procurement_cycle": "Often several months to a year, gated by field-trial results, safety review, and capital-budget cycles.",
        "sales_cycle": "Long and proof-heavy — a real field trial with measurable reliability/ROI data does the selling more than any specification sheet.",
        "enterprise_objections": ["What's the reliability/uptime track record in real field conditions?", "What's the safety certification/compliance status?", "What's the maintenance and support plan once deployed?"],
        "smb_objections": ["Is the capital cost justified at our smaller scale/volume?"],
        "pilot_strategy": "One site or production line, with real hardware deployed for a defined trial period, measured against uptime, cost, or safety outcomes.",
        "expansion_path": "Prove reliability and ROI at one site, then expand to additional sites/units within the same operator before pursuing new customers.",
        "expansion_triggers": ["A field trial clearing the operator's safety/reliability bar", "Capital-budget cycle alignment for a larger rollout"],
        "customer_acquisition_channels": ["Industrial/trade conferences and associations", "Direct outreach to operations/engineering leadership", "Referrals between site operators"],
        "retention_strategy": "Reliability and responsive maintenance/support are the retention lever — hardware failures in the field are far more costly to trust than a software bug.",
        "common_pricing_approaches": ["Upfront hardware cost plus ongoing service/subscription", "Per-unit or per-site licensing with maintenance included"],
        "common_failure_reasons": ["Underestimating field-condition reliability versus lab/demo conditions", "No clear safety/compliance certification story", "Capital cost not justified without a proven field trial"],
        "common_competitive_advantages": ["Demonstrated field reliability under real operating conditions", "Safety/compliance certification readiness", "A responsive maintenance/support model"],
        "enterprise_readiness_checklist": ["Safety/compliance certification appropriate to the deployment environment", "Demonstrated field reliability data", "A maintenance/support plan for deployed units"],
        "regulatory_considerations": "Safety and equipment-certification regulations specific to the deployment environment (industrial, energy, aerospace, or construction), which vary significantly by sub-domain.",
        "technical_stack_expectations": "Integration with existing industrial control/monitoring systems; must perform reliably in real field conditions, not just controlled test environments.",
        "typical_differentiation": "Demonstrated field reliability and safety/compliance readiness, more than raw specification or feature count.",
        "common_feature_roadmap": ["Start with one physical process/use case", "Add reliability/monitoring instrumentation", "Add safety/compliance certification", "Expand to multi-site/fleet deployment"],
    },
    "foodtech": {
        "typical_customer": "A restaurant, canteen, or food-service kitchen/operations manager.",
        "buying_process": "A single kitchen or site operations manager typically decides directly, without a broader procurement process — the fastest buying cycle among these categories.",
        "customer_journey": ["Manager feels daily inventory/ordering/waste pain", "Informal trial at one site", "Manager decides directly", "Word-of-mouth referral to other site managers"],
        "common_integrations": ["POS systems", "Existing inventory/ordering software"],
        "expected_kpis": ["Waste reduction (by item)", "Time saved on manual ordering/inventory checks", "Order/stock-out accuracy"],
        "procurement_difficulty": "low for a single independent site; medium for multi-site corporate/campus operators who require a facilities or procurement sign-off.",
        "procurement_cycle": "Days to a few weeks for an independent site; a full budget cycle for multi-site/corporate operators.",
        "sales_cycle": "Fast and pragmatic — a manager decides based on a real trial result, not a long evaluation process.",
        "enterprise_objections": ["Does this integrate with our existing POS/ordering system?", "Will kitchen staff actually use this daily?", "What happens during a system outage at meal service time?"],
        "smb_objections": ["Is this worth it for a single small kitchen or independent restaurant?"],
        "pilot_strategy": "One kitchen or site, running for a few weeks, with waste or ordering-time reduction as the single measurable outcome.",
        "expansion_path": "Prove the outcome at one site, then expand to other sites operated by the same manager/owner before selling to a new operator.",
        "expansion_triggers": ["A measurable waste/time-savings result at the pilot site", "A second site manager under the same owner requesting access"],
        "customer_acquisition_channels": ["Word-of-mouth between site/kitchen managers", "Food-service trade shows/associations", "Direct outreach to multi-site operators"],
        "retention_strategy": "Keep the daily workflow friction low so kitchen staff keep using it; renew by showing ongoing waste/cost savings.",
        "common_pricing_approaches": ["Per-site or per-meal-volume pricing"],
        "common_failure_reasons": ["Underestimating how disruptive any new system is during active meal-service hours", "No real integration with the site's existing POS/ordering flow", "Proving value at one site but failing to convert it into a repeatable sales motion"],
        "common_competitive_advantages": ["Direct POS/ordering integration", "Proven waste/cost reduction at a real site", "Low day-to-day operational friction for kitchen staff"],
        "enterprise_readiness_checklist": ["Multi-site administration", "POS/ordering system integration", "Reliable operation during active meal-service hours"],
        "regulatory_considerations": "Food-safety recordkeeping expectations where the tool touches inventory/handling data, though this is typically lighter-touch than clinical or financial regulation.",
        "technical_stack_expectations": "Integration with common POS and inventory/ordering systems; must be simple enough for kitchen staff to use without training overhead.",
        "typical_differentiation": "Real POS/ordering integration and a proven waste/cost result at an actual site, plus low day-to-day friction for staff.",
        "common_feature_roadmap": ["Start with one workflow (inventory, ordering, or waste tracking)", "Add POS integration", "Add multi-site reporting", "Expand to predictive ordering"],
    },
    "logistics": {
        "typical_customer": "An operations or fleet manager responsible for routes, hubs, or delivery performance.",
        "buying_process": "An operations or fleet manager evaluates against clear, already-tracked cost/time metrics — a numbers-driven sale.",
        "customer_journey": ["Manager identifies a routing/dispatch inefficiency", "Pilot on one route or hub", "Comparison against existing cost-per-delivery/on-time metrics", "Rollout to additional routes/hubs"],
        "common_integrations": ["Order-management or e-commerce platforms", "Existing fleet/dispatch software"],
        "expected_kpis": ["On-time delivery rate", "Cost per delivery", "Fuel/time saved per route"],
        "procurement_difficulty": "medium — usually a single operations decision-maker, but real integration work with existing systems can slow things down.",
        "procurement_cycle": "Weeks for a single-route pilot; a couple of months for multi-route/hub rollout pending integration work.",
        "sales_cycle": "Metrics-driven and fast once a real pilot shows measurable cost/time improvement.",
        "enterprise_objections": ["Does this integrate with our existing order-management system?", "What happens if the optimization suggests something a driver can't actually execute?", "How much disruption during rollout to an active route?"],
        "smb_objections": ["Is this worth it for a small operator with only a few vehicles/routes?"],
        "pilot_strategy": "One route or hub, measured against the operator's own existing cost-per-delivery/on-time numbers.",
        "expansion_path": "Prove cost/time savings on one route or hub, then expand to additional routes/hubs within the same operator.",
        "expansion_triggers": ["A measurable cost or on-time improvement on the pilot route/hub", "Operations leadership requesting expansion to more routes"],
        "customer_acquisition_channels": ["Logistics/fleet-management trade shows", "Referrals between operations managers", "Direct outreach to fleet/logistics operators"],
        "retention_strategy": "Continued, measurable cost/on-time improvement; renewal tracks with the operator's own performance dashboards.",
        "common_pricing_approaches": ["Per-vehicle or per-delivery pricing"],
        "common_failure_reasons": ["Optimization that looks good on paper but isn't operationally executable by real drivers", "No integration with the existing order-management flow", "Underestimating the cost of proving ROI convincingly enough to expand beyond the first route"],
        "common_competitive_advantages": ["Real-time replanning (not just static routes)", "Direct integration with existing order/dispatch systems", "Demonstrated cost/time savings on a real route"],
        "enterprise_readiness_checklist": ["Multi-route/hub administration", "Order-management/dispatch system integration", "Real-time replanning reliability"],
        "regulatory_considerations": "Driver hours-of-service and vehicle-safety regulations where the tool influences routing/dispatch decisions, and data handling for delivery/customer address data.",
        "technical_stack_expectations": "Integration with existing order-management and fleet/dispatch systems; needs to be operationally executable, not just mathematically optimal.",
        "typical_differentiation": "Real-time, operationally executable replanning and demonstrated cost/time savings on an actual route, not a simulated one.",
        "common_feature_roadmap": ["Start with one optimization type (routing or scheduling)", "Add order-management integration", "Add real-time replanning", "Expand to multi-route/hub administration"],
    },
    "marketplace": {
        "typical_customer": "Both a supply-side participant and a demand-side participant — there is no single buyer persona.",
        "buying_process": "No single 'buyer' — both a supply-side and a demand-side participant must independently choose to show up, which is the core chicken-and-egg buying challenge.",
        "customer_journey": ["Supply-side participant onboards", "Demand-side participant discovers/tries the marketplace", "First successful match/transaction", "Repeat usage on both sides"],
        "common_integrations": ["Payment/payout processing", "Identity/verification providers"],
        "expected_kpis": ["Liquidity (successful matches per category/region)", "Take-rate revenue", "Repeat usage rate on both sides"],
        "procurement_difficulty": "low individually (self-serve signup on both sides), but structurally hard because BOTH sides must reach critical mass simultaneously.",
        "procurement_cycle": "Immediate/self-serve per participant, but reaching a workable pilot often requires manually recruiting both sides in parallel.",
        "sales_cycle": "Not a traditional sales cycle — more a liquidity-building exercise, often requiring hands-on recruiting of both sides early on.",
        "enterprise_objections": ["Why would supply-side participants join before there's real demand, and vice versa?", "How do you prevent transactions moving off-platform?", "What's your plan for a thin/imbalanced category or region?"],
        "smb_objections": ["Is it worth joining a marketplace with limited activity in my category/region yet?"],
        "pilot_strategy": "One narrow category or region with both sides manually recruited (often by hand, not through the product) to prove a real match can happen.",
        "expansion_path": "Prove liquidity in one narrow category/region, then expand category-by-category or region-by-region rather than broadly all at once.",
        "expansion_triggers": ["Demonstrated repeat matches/transactions in the pilot category/region", "A supply-side surplus or demand-side surplus signaling readiness to expand"],
        "customer_acquisition_channels": ["Hand-recruiting both sides directly in the pilot niche", "Referrals from early participants on each side", "Niche community/industry channels for the target category"],
        "retention_strategy": "Keep transactions on-platform by making off-platform dealing riskier or less convenient than staying; keep both sides engaged through repeat successful matches.",
        "common_pricing_approaches": ["Transaction take-rate", "Featured/priority-placement fees on the supply side"],
        "common_failure_reasons": ["Trying to launch broadly before proving liquidity in one narrow niche", "Transactions leaking off-platform, losing the take-rate", "Recruiting one side without a concrete plan for the other"],
        "common_competitive_advantages": ["Proven liquidity in a specific niche", "On-platform payment/trust infrastructure", "Supply-side quality/verification"],
        "enterprise_readiness_checklist": ["N/A in the traditional sense — the closest equivalent is trust/verification infrastructure robust enough for larger supply-side or demand-side accounts."],
        "regulatory_considerations": "Payment/escrow handling for on-platform transactions, and identity-verification obligations depending on the category (e.g. regulated goods/services).",
        "technical_stack_expectations": "Reliable payment/payout processing and identity/verification integration; needs to support both sides of the marketplace with different interfaces.",
        "typical_differentiation": "Demonstrated liquidity in a specific niche and trust/verification infrastructure that keeps transactions on-platform.",
        "common_feature_roadmap": ["Start with one narrow category/region", "Add on-platform payment/escrow", "Add trust/verification features", "Expand category-by-category or region-by-region"],
    },
    "developer_tools": {
        "typical_customer": "An individual developer or small engineering team, with org-wide adoption as a later stage.",
        "buying_process": "An individual developer or small engineering team adopts bottom-up first; a team/org-wide purchase decision comes later, often driven by an engineering lead, not procurement.",
        "customer_journey": ["Individual developer discovers and tries the tool", "Integrates it into a real project", "Advocates for team-wide adoption", "Org-wide rollout with SSO/admin controls"],
        "common_integrations": ["CI/CD pipelines", "Existing toolchain (IDE, version control, issue tracker)"],
        "expected_kpis": ["Time-to-first-success for a new user", "Active usage (builds/API calls/seats-active)", "Retention after initial adoption"],
        "procurement_difficulty": "low for individual adoption; medium for org-wide rollout, usually gated by a security/IT review (SSO, audit logging).",
        "procurement_cycle": "Immediate for individual/bottom-up adoption; weeks-to-months for team/org-wide procurement pending security review.",
        "sales_cycle": "Product-led — usage and developer advocacy drive the sale more than a traditional sales process.",
        "enterprise_objections": ["Does this have SSO and audit logging for org-wide rollout?", "How does this fit into our existing CI/CD pipeline?", "What's the migration/lock-in risk if we adopt this?"],
        "smb_objections": ["Is the paid tier worth it over the free/individual tier for a small team?"],
        "pilot_strategy": "One individual developer or small team integrating it into a real, active project — not a sandboxed demo.",
        "expansion_path": "Prove value with one developer/team, then expand to team-wide, then org-wide with the admin/security features that unlocks.",
        "expansion_triggers": ["Sustained individual/team usage over time", "A team lead requesting seats/admin controls for wider rollout"],
        "customer_acquisition_channels": ["Developer communities (forums, open-source, technical content)", "Word-of-mouth/referral among developers", "Integration marketplaces/directories"],
        "retention_strategy": "Keep time-to-value low and stay embedded in the daily developer workflow; retention is usage-driven more than relationship-driven.",
        "common_pricing_approaches": ["Usage-based (API calls, builds)", "Per-seat pricing with a team/org tier"],
        "common_failure_reasons": ["Strong individual adoption that never converts to a paid team tier", "Missing SSO/audit logging blocking org-wide rollout", "Too much required setup before a new user sees value"],
        "common_competitive_advantages": ["Fast time-to-first-success", "Native integration with the existing toolchain", "A credible security/admin story for org-wide rollout"],
        "enterprise_readiness_checklist": ["SSO and audit logging", "Admin/user-management controls", "Migration path with low lock-in risk"],
        "regulatory_considerations": "Data residency/handling expectations where the tool processes code or customer data, and license-compliance considerations for any dependencies it introduces.",
        "technical_stack_expectations": "Integration with common CI/CD pipelines and toolchains (IDE, version control, issue tracker); low-friction setup is a functional requirement, not a nicety.",
        "typical_differentiation": "Speed of time-to-first-success and how natively it fits the existing developer toolchain.",
        "common_feature_roadmap": ["Start with one integration point (CLI, API, or IDE plugin)", "Add CI/CD integration", "Add team collaboration features", "Expand to org-wide admin/security controls"],
    },
    "education": {
        "typical_customer": "An individual teacher or program lead, with institution-wide adoption as a later stage.",
        "buying_process": "An individual teacher/program lead adopts first; broader institutional purchase requires an administrator and often a procurement/FERPA review.",
        "customer_journey": ["Teacher/program lead discovers the tool", "Classroom or cohort pilot", "Informal results shared with department/administration", "Institutional procurement review", "Program/department-wide rollout"],
        "common_integrations": ["School/university LMS (roster sync, grade passback)"],
        "expected_kpis": ["Learner engagement/completion rate", "Instructor time saved (grading, tracking)", "Learning outcome improvement"],
        "procurement_difficulty": "medium-to-high for institution-wide adoption — FERPA/data-handling and procurement review are real gates, even when the teacher-level pilot itself was easy.",
        "procurement_cycle": "Weeks for a single classroom pilot; a full academic budget cycle (often a semester or year) for institution-wide adoption.",
        "sales_cycle": "Bottom-up and evidence-driven — a teacher's classroom results are the strongest lever for institutional advocacy.",
        "enterprise_objections": ["Is this FERPA-compliant?", "Does this integrate with our LMS for roster/grade sync?", "What happens to student data after they leave the program?"],
        "smb_objections": ["Is this worth it for a small school or independent tutor/program?"],
        "pilot_strategy": "One classroom or cohort with one teacher/program lead, measured against a concrete learning or engagement outcome.",
        "expansion_path": "Prove the outcome in one classroom, then expand to adjacent classrooms/subjects before pursuing institution-wide procurement.",
        "expansion_triggers": ["A documented learning-outcome or engagement improvement", "A department/administration requesting evaluation for wider rollout"],
        "customer_acquisition_channels": ["Education conferences and teacher communities", "Referrals between teachers/program leads", "Direct outreach to department administrators"],
        "retention_strategy": "Demonstrated learning-outcome impact reviewed at each academic term/budget cycle; LMS integration raises switching costs once adopted.",
        "common_pricing_approaches": ["Per-student or per-classroom pricing", "Program/department-wide licensing"],
        "common_failure_reasons": ["Strong classroom-level results that never clear institutional procurement", "No FERPA-aligned data handling story ready when asked", "Underestimating how slow institutional budget cycles are"],
        "common_competitive_advantages": ["LMS integration", "FERPA-aligned data handling", "Demonstrated learning-outcome improvement, not just engagement"],
        "enterprise_readiness_checklist": ["FERPA-aligned data handling", "LMS integration (roster/grade sync)", "Institution-wide administration controls"],
        "regulatory_considerations": "Student data privacy (FERPA-equivalent), and accessibility requirements for any learner-facing interface.",
        "technical_stack_expectations": "Integration with common LMS platforms for roster sync and grade passback; accessible design for diverse learners.",
        "typical_differentiation": "Demonstrated learning-outcome improvement (not just engagement) plus a FERPA-aligned, LMS-integrated story for institutional buyers.",
        "common_feature_roadmap": ["Start with one learning activity/workflow", "Add LMS integration", "Add outcome/engagement reporting", "Expand to institution-wide administration"],
    },
    "consumer": {
        "typical_customer": "An individual end user who is both the buyer and the user.",
        "buying_process": "Individual, self-serve — the 'buyer' and the user are the same person, and the decision is usually fast and low-stakes compared to every other category here.",
        "customer_journey": ["Discovery (organic, social, referral)", "First-use activation", "Habitual/repeat use", "Conversion from free to paid (if freemium)"],
        "common_integrations": ["Platforms users already use daily (calendar, messaging, social login)"],
        "expected_kpis": ["Activation rate", "Retention/repeat-use rate", "Free-to-paid conversion rate (if applicable)"],
        "procurement_difficulty": "very low — no institutional buyer, but retention/habit-formation is the hard part instead.",
        "procurement_cycle": "Immediate — a user decides in a single session.",
        "sales_cycle": "Not a traditional sales cycle — growth/marketing-driven rather than sales-driven.",
        "enterprise_objections": ["N/A — consumer products rarely face an institutional buyer's objections; the equivalent concern is user trust/privacy."],
        "smb_objections": ["N/A — consumer products don't typically have an SMB buyer distinct from the individual user."],
        "pilot_strategy": "A small early-adopter cohort, testing whether repeat/habitual use actually happens, not just a one-time trial.",
        "expansion_path": "Prove habitual use in a narrow early-adopter group, then broaden acquisition channels once retention (not just signups) is real.",
        "expansion_triggers": ["A demonstrated repeat/habitual usage pattern in the early-adopter cohort", "A validated, repeatable acquisition channel"],
        "customer_acquisition_channels": ["Organic/word-of-mouth and referral", "Social/content marketing", "App-store or platform discovery"],
        "retention_strategy": "Build genuine habit-forming usage and keep the premium tier's value obviously ahead of the free tier.",
        "common_pricing_approaches": ["Freemium with a valuable premium unlock", "Simple flat subscription"],
        "common_failure_reasons": ["Strong initial signups that don't translate into repeat/habitual use", "A premium tier that doesn't feel meaningfully more valuable than free", "Acquisition-channel dependency (e.g. one social platform) without a retention story"],
        "common_competitive_advantages": ["Genuine habit-forming daily/weekly use", "Integration with platforms users already use", "A premium tier with real, felt value"],
        "enterprise_readiness_checklist": ["N/A — consumer products generally do not pursue enterprise-readiness features."],
        "regulatory_considerations": "Consumer data privacy regulations, and age-appropriate design considerations if the product may attract minor users.",
        "technical_stack_expectations": "Integration with platforms users already use daily (social login, calendar, messaging); low-friction onboarding is a functional requirement.",
        "typical_differentiation": "Genuine habit-forming usage and a premium tier whose value is felt immediately, not just claimed.",
        "common_feature_roadmap": ["Start with one core habit-forming action", "Add a premium tier with clearly differentiated value", "Add social/referral mechanics", "Expand acquisition-channel integrations"],
    },
    "b2b": {
        "typical_customer": "A team or department within a company, with an economic buyer distinct from the daily user.",
        "buying_process": "An economic buyer (often not the daily user) approves budget, usually after the daily-user champion has already validated the tool internally.",
        "customer_journey": ["Team member/champion discovers the tool and tries it informally", "Champion advocates internally", "Economic buyer/manager approves budget", "Team-wide rollout", "Renewal decision based on adoption/ROI"],
        "common_integrations": ["The tool the customer already uses for this workflow today"],
        "expected_kpis": ["Adoption rate within the team", "Time/cost saved on the automated workflow", "Renewal/expansion rate"],
        "procurement_difficulty": "medium — typically one champion plus one budget approver, with a security/procurement review for larger deals.",
        "procurement_cycle": "Weeks for a small team pilot; a couple of months for larger deals requiring security/procurement review.",
        "sales_cycle": "Champion-led — internal advocacy from a daily user typically precedes and shapes the formal sales conversation.",
        "enterprise_objections": ["Do you have SSO, audit logging, and admin user management?", "How does this integrate with what we already use for this workflow?", "What's the migration effort and lock-in risk?"],
        "smb_objections": ["Is this worth it for a small team without a dedicated budget line?"],
        "pilot_strategy": "One team or department, with a design-partner-style pilot proving a concrete time/cost saving before wider rollout.",
        "expansion_path": "Prove ROI in one team/department, then expand to adjacent departments within the same account before pursuing new accounts.",
        "expansion_triggers": ["A documented ROI result the champion can present to the economic buyer", "An adjacent team requesting access after seeing results"],
        "customer_acquisition_channels": ["Direct outreach to team leads/champions", "Industry conferences and communities", "Referrals from existing champions to peers at other companies"],
        "retention_strategy": "Demonstrate ongoing ROI ahead of each renewal; integration with the team's existing workflow raises switching costs.",
        "common_pricing_approaches": ["Per-seat pricing", "Per-workflow or usage-based pricing that scales with team size"],
        "common_failure_reasons": ["A champion who loves the tool but can't get budget approval", "No integration with the customer's existing workflow tool", "Missing the security/admin features a larger deal requires"],
        "common_competitive_advantages": ["Integration with the customer's existing workflow", "A clear, provable ROI story for the economic buyer", "Enterprise-readiness (SSO, audit logging, admin controls)"],
        "enterprise_readiness_checklist": ["SSO and audit logging", "Admin/user management controls", "Documented security/compliance posture"],
        "regulatory_considerations": "Data handling expectations tied to whatever workflow the tool touches (e.g. customer data, financial data), and standard vendor-security review requirements.",
        "technical_stack_expectations": "Integration with the tool(s) the customer already uses for this workflow; SSO/admin controls expected for anything beyond a small pilot.",
        "typical_differentiation": "A clear, provable ROI story for the economic buyer plus real integration with the customer's existing workflow.",
        "common_feature_roadmap": ["Start with one workflow automation", "Add team collaboration features", "Add admin/security controls (SSO, audit logging)", "Expand to adjacent workflows/departments"],
    },
}

_GENERIC_PACK = {
    "typical_customer": "Unclear from the category alone — likely an individual user or a team lead within a company.",
    "buying_process": "Unclear from the category alone — typically an individual user or team lead trials it first, with a separate approval step for anything beyond individual use.",
    "customer_journey": ["User discovers the problem/tool", "Informal trial", "Internal advocacy (if applicable)", "Wider adoption"],
    "common_integrations": ["The tool/workflow the user already relies on for this task today"],
    "expected_kpis": ["Adoption/usage rate", "Time or cost saved", "Retention/repeat-use rate"],
    "procurement_difficulty": "unclear without more category specificity — assume at least one approval step beyond the initial user.",
    "procurement_cycle": "Unclear without more category specificity — assume at least a few weeks between individual trial and any broader approval.",
    "sales_cycle": "Unclear without more category specificity — likely proof-driven, requiring a real trial result before expansion.",
    "enterprise_objections": ["How does this integrate with what we already use?", "What happens to our data if you shut down?", "Who else like us is already using this?"],
    "smb_objections": ["Is this worth the cost/effort for a small team or business?"],
    "pilot_strategy": "One real user or site, measured against one concrete, pre-defined outcome.",
    "expansion_path": "Prove the outcome with one real user/site before expanding to others.",
    "expansion_triggers": ["A demonstrated concrete outcome from the pilot", "A second user/site requesting access"],
    "customer_acquisition_channels": ["Word-of-mouth/referral", "Direct outreach to likely early users"],
    "retention_strategy": "Keep delivering the demonstrated outcome and stay integrated with the user's existing workflow.",
    "common_pricing_approaches": ["Usage-based or tiered pricing scaled to the value delivered"],
    "common_failure_reasons": ["Proving value with one user but never converting it into a repeatable sales motion", "No integration with the user's existing workflow"],
    "common_competitive_advantages": ["Integration with the user's existing workflow", "A clear, demonstrated outcome from a real pilot"],
    "enterprise_readiness_checklist": ["Basic security/access controls", "A documented data-handling practice"],
    "regulatory_considerations": "Unclear without more category specificity — assume standard data-privacy expectations apply.",
    "technical_stack_expectations": "Unclear without more category specificity — assume integration with whatever tool the user relies on today.",
    "typical_differentiation": "A clear, demonstrated outcome from a real pilot, more than feature count.",
    "common_feature_roadmap": ["Start with one core workflow", "Add integration with the user's existing tools", "Add reporting", "Expand based on real adoption signals"],
}

_REQUIRED_FIELDS = (
    "typical_customer", "buying_process", "customer_journey", "common_integrations", "expected_kpis",
    "procurement_difficulty", "procurement_cycle", "sales_cycle", "enterprise_objections", "smb_objections",
    "pilot_strategy", "expansion_path", "expansion_triggers", "customer_acquisition_channels",
    "retention_strategy", "common_pricing_approaches", "common_failure_reasons", "common_competitive_advantages",
    "enterprise_readiness_checklist", "regulatory_considerations", "technical_stack_expectations",
    "typical_differentiation", "common_feature_roadmap",
)
for _category, _pack in _PACKS.items():
    _missing = [f for f in _REQUIRED_FIELDS if f not in _pack]
    if _missing:
        raise AssertionError(f"industry knowledge pack '{_category}' is missing required fields: {_missing}")
_missing_generic = [f for f in _REQUIRED_FIELDS if f not in _GENERIC_PACK]
if _missing_generic:
    raise AssertionError(f"generic industry knowledge pack is missing required fields: {_missing_generic}")


def get_industry_knowledge_pack(
    primary_domain: str | None,
    model_category_label: str | None,
    deployment_sectors: list[str] | None = None,
    startup_description: str | None = None,
) -> dict:
    """Returns the knowledge pack for this venture's resolved category (never a per-venture
    inference — the same deterministic category resolution every other category-flavored module
    already uses). Every field is general startup-domain knowledge, explicitly labeled as such —
    never a claim about this specific venture or a specific real company."""
    category = resolve_category(primary_domain, model_category_label, deployment_sectors, startup_description)
    pack = _PACKS.get(category, _GENERIC_PACK)
    return {
        "industry_knowledge_pack_version": INDUSTRY_KNOWLEDGE_PACK_VERSION,
        "category": category,
        **pack,
        "source": (
            f"General startup-domain knowledge for '{category}' ventures — hand-curated, "
            "qualitative patterns (no invented statistics, prices, or named companies), the same "
            "kind of category-level reference data app.agents.go_to_market_intelligence/"
            "pricing_intelligence/feature_intelligence already rely on. Never a claim about this "
            "specific venture."
        ),
    }


def supported_categories() -> list[str]:
    """All categories this knowledge base has a dedicated (non-generic) pack for — used by the
    Phase 1/7 knowledge coverage audit to report real category coverage against the full taxonomy
    app.agents.venture_vocabulary.resolve_category can produce."""
    return sorted(_PACKS.keys())
