import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { Analysis } from "../types/api";
import { deriveFounderDecision } from "./founderDecision";
import { buildInsights, findInsight } from "./insights";

const PAGE_W = 595.28; // A4 in points
const PAGE_H = 841.89;
const MARGIN = 44;
const CONTENT_W = PAGE_W - MARGIN * 2;
const PURPLE = rgb(0.545, 0.361, 0.965);
const GOLD = rgb(1, 0.69, 0.13);
const INK = rgb(0.09, 0.08, 0.15);
const MUTED = rgb(0.43, 0.41, 0.51);
const RULE = rgb(0.9, 0.9, 0.93);

/** Real, structured multi-page PDF — replaces the previous raw-JSON download entirely. Built with
 * `pdf-lib` (drawn text/lines, not a screenshot of the rendered page): `jspdf` was tried first but
 * its main bundle statically pulls in `html2canvas`/`dompurify`/`canvg` regardless of whether
 * `.html()` is ever called — a known packaging issue that added ~260KB gzipped to this one route
 * for zero benefit here. `pdf-lib` has no such baggage and is purpose-built for exactly this kind
 * of programmatic layout. Every value comes from the same `Analysis`/`MentorInterpretation`
 * objects already rendered on the Reveal page — sections whose backing field is null (no
 * `founder_report`, no revenue estimate, etc.) are simply omitted, never filled with placeholder
 * text.
 *
 * Sections flow continuously rather than each forcing its own page: a short section (e.g.
 * Dashboard, three label/value pairs) used to leave most of a page blank before Top Priorities
 * started fresh on the next one. `sectionBreak()` only starts a new page when the next section
 * genuinely doesn't fit in the remaining space — otherwise it draws a hairline divider and
 * continues on the same page, so related content stays together and no page is left mostly empty.
 * Only the cover page is always its own page (a report's cover is a real, intentional convention,
 * not wasted space). */
export async function generateAnalysisPdf(analysis: Analysis, startupName: string | null) {
  const mentor = analysis.mentor_interpretation;
  if (!mentor) return;

  const pdf = await PDFDocument.create();
  const regular = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);

  const insights = buildInsights(analysis, mentor);
  const decision = deriveFounderDecision(mentor);
  const industry = analysis.industry_prediction?.primary_industry ?? analysis.industry_prediction?.predicted_industry ?? null;
  const name = startupName ?? "Your Venture";

  let page = pdf.addPage([PAGE_W, PAGE_H]);
  let y = MARGIN;
  let pageIndex = 0;

  function wrap(text: string, font: typeof regular, size: number, maxWidth: number): string[] {
    const words = text.split(/\s+/);
    const lines: string[] = [];
    let current = "";
    for (const word of words) {
      const attempt = current ? `${current} ${word}` : word;
      if (font.widthOfTextAtSize(attempt, size) > maxWidth && current) {
        lines.push(current);
        current = word;
      } else {
        current = attempt;
      }
    }
    if (current) lines.push(current);
    return lines;
  }

  function drawFooter() {
    page.drawText(`Generated by VentureForge.AI — ${new Date().toLocaleDateString()}`, {
      x: MARGIN,
      y: 26,
      size: 8,
      font: regular,
      color: MUTED,
    });
    const pageLabel = `Page ${pageIndex}`;
    const w = regular.widthOfTextAtSize(pageLabel, 8);
    page.drawText(pageLabel, { x: PAGE_W - MARGIN - w, y: 26, size: 8, font: regular, color: MUTED });
  }

  function newPage() {
    if (pageIndex > 0) drawFooter();
    page = pdf.addPage([PAGE_W, PAGE_H]);
    pageIndex += 1;
    if (pageIndex > 1) {
      // The cover page carries its own large wordmark treatment — this compact running header is
      // for every content page after it.
      page.drawText("VentureForge.AI", { x: MARGIN, y: PAGE_H - 36, size: 10, font: bold, color: PURPLE });
      const labelW = regular.widthOfTextAtSize("Venture Analysis Report", 9);
      page.drawText("Venture Analysis Report", { x: PAGE_W - MARGIN - labelW, y: PAGE_H - 35, size: 9, font: regular, color: MUTED });
      page.drawLine({ start: { x: MARGIN, y: PAGE_H - 46 }, end: { x: PAGE_W - MARGIN, y: PAGE_H - 46 }, thickness: 0.5, color: RULE });
      y = PAGE_H - 66;
    } else {
      y = PAGE_H - 40;
    }
  }

  function ensureSpace(needed: number) {
    if (y - needed < MARGIN + 30) newPage();
  }

  /** Starts a new named section — only breaks to a fresh page when the section's estimated
   * minimum height (heading + first real block) genuinely won't fit in what's left, otherwise
   * continues on the current page after a hairline divider, so short adjacent sections share a
   * page instead of each claiming one. */
  function sectionBreak(text: string, minHeight: number, size = 17) {
    const pageBefore = pageIndex;
    const freshAlready = y > PAGE_H - 100; // e.g. right after the explicit newPage() before Executive Summary
    ensureSpace(minHeight);
    const pageJustBroke = pageIndex !== pageBefore;
    if (!freshAlready && !pageJustBroke) {
      // Still on the same page as the previous section — mark the boundary with a divider rather
      // than letting one section's content run straight into the next with no separation.
      y -= 4;
      page.drawLine({ start: { x: MARGIN, y }, end: { x: PAGE_W - MARGIN, y }, thickness: 0.75, color: RULE });
      y -= 22;
    }
    const lines = wrap(text, bold, size, CONTENT_W);
    for (const line of lines) {
      page.drawText(line, { x: MARGIN, y, size, font: bold, color: INK });
      y -= size * 1.25;
    }
    y -= 8;
  }

  function label(text: string, color = PURPLE) {
    page.drawText(text.toUpperCase(), { x: MARGIN, y, size: 9, font: bold, color });
    y -= 13;
  }

  function body(text: string, size = 11) {
    const lines = wrap(text, regular, size, CONTENT_W);
    for (const line of lines) {
      page.drawText(line, { x: MARGIN, y, size, font: regular, color: INK });
      y -= size * 1.35;
    }
    y -= 5;
  }

  // ---- Cover page ----
  newPage();
  y = PAGE_H / 2 + 60;
  const coverTitle = "VentureForge.AI";
  const titleSize = 32;
  const titleW = bold.widthOfTextAtSize(coverTitle, titleSize);
  page.drawText(coverTitle, { x: (PAGE_W - titleW) / 2, y, size: titleSize, font: bold, color: PURPLE });
  y -= 40;
  const nameSize = 22;
  const nameW = bold.widthOfTextAtSize(name, nameSize);
  page.drawText(name, { x: (PAGE_W - nameW) / 2, y, size: nameSize, font: bold, color: INK });
  y -= 24;
  const subtitle = [industry, new Date().toLocaleDateString()].filter(Boolean).join("  ·  ");
  const subtitleW = regular.widthOfTextAtSize(subtitle, 12);
  page.drawText(subtitle, { x: (PAGE_W - subtitleW) / 2, y, size: 12, font: regular, color: MUTED });
  y -= 30;
  const tagline = "Founder Operating System — Venture Analysis Report";
  const taglineW = regular.widthOfTextAtSize(tagline, 11);
  page.drawText(tagline, { x: (PAGE_W - taglineW) / 2, y, size: 11, font: regular, color: MUTED });

  // ---- Executive Summary ----
  newPage();
  sectionBreak("Executive Summary", 200);
  body(mentor.mentor_verdict.concise_verdict, 12);
  label("Investment ready?");
  body(decision.label);
  const successPct = analysis.success_prediction ? Math.round(analysis.success_prediction.success_probability * 100) : null;
  const fundingScore = analysis.funding_assessment?.overall_score ?? null;
  if (successPct !== null) {
    label("Success probability", GOLD);
    body(`${successPct}%`);
  }
  if (fundingScore !== null) {
    label("Funding readiness", GOLD);
    body(`${fundingScore}/100`);
  }
  const strength = findInsight(insights, "insight-biggest-strength");
  const risk = findInsight(insights, "insight-biggest-risk");
  const priority = findInsight(insights, "insight-immediate-priority");
  if (strength) {
    label("Biggest strength");
    body(strength.why);
  }
  if (risk) {
    label("Biggest risk");
    body(risk.why);
  }
  if (priority) {
    label("Immediate next step");
    body(priority.why);
  }

  // ---- Dashboard ----
  if (analysis.funding_assessment || analysis.success_prediction || analysis.industry_prediction) {
    sectionBreak("Dashboard", 140);
    if (analysis.funding_assessment) {
      label(`Funding readiness — ${analysis.funding_assessment.overall_score}/100`, GOLD);
      body(analysis.funding_assessment.level.replace(/_/g, " "));
    }
    if (analysis.success_prediction) {
      label(`Success probability — ${Math.round(analysis.success_prediction.success_probability * 100)}%`);
      body(analysis.success_prediction.pattern_signal_display);
    }
    if (analysis.industry_prediction) {
      label(`Industry — ${industry ?? "unclassified"}`);
      body(`Confidence: ${Math.round((analysis.industry_prediction.primary_confidence ?? analysis.industry_prediction.confidence) * 100)}%`);
    }
  }

  // ---- Top 3 Missions ----
  const missions = mentor.founder_report?.founder_strategy.slice(0, 3) ?? [];
  if (missions.length > 0) {
    sectionBreak("Top 3 Priorities", 130);
    for (const m of missions) {
      ensureSpace(90);
      label(`Priority ${m.priority} — ${m.impact} impact, ${m.difficulty}, ${m.estimated_duration}`);
      body(m.action.content);
      body(`Definition of done: ${m.definition_of_done.content}`, 9.5);
    }
  }

  // ---- Investor Review ----
  const investorRows = mentor.founder_report?.investor_view.filter((r) => r.investor_question) ?? [];
  if (investorRows.length > 0) {
    sectionBreak("Investor Review", 150);
    label("Decision");
    body(decision.label);
    for (const row of investorRows) {
      ensureSpace(100);
      label("Question");
      body(row.investor_question?.content ?? "");
      body(`Concern: ${row.investor_concern.content}`, 9.5);
      body(`Evidence: ${row.evidence.content}`, 9.5);
    }
  }

  // ---- Appendix (condensed) ----
  sectionBreak("Appendix — Methodology & Evidence", 150, 15);
  body(
    "Every claim in this report is tagged as evidence (an established fact from what was submitted), " +
      "inference (a reasoned conclusion from that evidence), ai_recommendation (a suggestion, not a fact " +
      "about this venture), market_assumption (a general pattern assumed to apply), or " +
      "experiment_suggestion (a concrete test to run). Nothing here is fabricated market research, a " +
      "verified competitor database, or a live pricing feed.",
    9.5,
  );
  if (analysis.funding_assessment) {
    label("Funding readiness breakdown");
    for (const item of analysis.funding_assessment.breakdown) {
      ensureSpace(16);
      body(`${item.label}: ${item.raw_score ?? "N/A"} / ${item.max_score}`, 9.5);
    }
  }
  drawFooter();

  const bytes = await pdf.save();
  const blob = new Blob([bytes.buffer as ArrayBuffer], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = `venture-analysis-${analysis.id}.pdf`;
  link.click();
  URL.revokeObjectURL(url);
}
